blueprint:
  name: "[CDA] 🪟 Blind Control"
  description: "Control blinds with position presets (0%, 25%, 50%, 75%, 100%)"
  domain: automation
  input:
    blind_switch:
      name: "Blind Switch"
      description: "The switch entity that controls the blind"
      selector:
        entity:
          domain: switch
    last_state:
      name: "Last State"
      description: "Input text entity to store the last state of the blind"
      selector:
        entity:
          domain: input_text
    travel_time:
      name: "Travel Time"
      description: "Time in seconds for the blind to travel from fully closed to fully open"
      default: 30
      selector:
        number:
          min: 1
          max: 300
          step: 1
    target_position:
      name: "Target Position"
      description: "The position to set the blind to (0%, 25%, 50%, 75%, 100%)"
      selector:
        select:
          options:
            - "0% (Closed)"
            - "25%"
            - "50%"
            - "75%"
            - "100% (Open)"

trigger:
  platform: event
  event_type: select_option
  event_data:
    entity_id: !input target_position

action:
  - service: script.set_blind_position
    data:
      blind_switch: !input blind_switch
      last_state: !input last_state
      travel_time: !input travel_time
      target_position: !input target_position

mode: single 