blueprint:
  name: "[CDA] 🔔 Scheduled Bell Sound"
  description: "Play a sound at specific times with volume control"
  domain: automation
  input:
    media_player:
      name: "Media Player"
      description: "The media player to play the sound"
      selector:
        entity:
          domain: media_player
    sound_file:
      name: "Sound File"
      description: "The sound file to play (from media source)"
      selector:
        text:
    announce_volume:
      name: "Announce Volume Level"
      description: "The volume level to use for the announcement (0-1)"
      default: 0.5
      selector:
        number:
          min: 0
          max: 1
          step: 0.1
    volume_reduction:
      name: "Volume Reduction"
      description: "How much to reduce the volume for the announcement (0-1)"
      default: 0.2
      selector:
        number:
          min: 0
          max: 1
          step: 0.1
    wait_time:
      name: "Wait Time"
      description: "How long to wait after playing before restoring volume (seconds)"
      default: 20
      selector:
        number:
          min: 1
          max: 300
          step: 1
    triggers:
      name: "Triggers"
      description: "Triggers to play the sound"
      default: []
      selector:
        object:
          multiple: true
          options:
            platform:
              name: "Platform"
              description: "Trigger platform"
              selector:
                select:
                  options:
                    - time
                    - sun
                    - state
                    - event
                    - mqtt
                    - webhook
            at:
              name: "Time"
              description: "Time to trigger (HH:MM)"
              selector:
                time:
            event:
              name: "Sun Event"
              description: "Sun event to trigger on"
              selector:
                select:
                  options:
                    - sunrise
                    - sunset
            offset:
              name: "Offset"
              description: "Offset from the event (e.g. -00:30:00 for 30 minutes before)"
              default: "00:00:00"
              selector:
                text:
            entity_id:
              name: "Entity"
              description: "Entity to monitor"
              selector:
                entity:
            from:
              name: "From State"
              description: "State to trigger from"
              selector:
                text:
            to:
              name: "To State"
              description: "State to trigger to"
              selector:
                text:
            event_type:
              name: "Event Type"
              description: "Event type to trigger on"
              selector:
                text:
            topic:
              name: "Topic"
              description: "MQTT topic to monitor"
              selector:
                text:
            payload:
              name: "Payload"
              description: "MQTT payload to match"
              selector:
                text:

trigger: !input triggers

action:
  - service: script.play_sound_with_volume_control
    data:
      media_player: !input media_player
      sound_file: !input sound_file
      announce_volume: !input announce_volume
      volume_reduction: !input volume_reduction
      wait_time: !input wait_time

mode: single 