blueprint:
  name: "[CDA] 🔔 Scheduled Bell Sound"
  description: "Play a sound at specific times with volume control"
  domain: automation
  input:
    media_player:
      name: "Media Player"
      description: "The media player to play the sound"
      selector:
        entity:
          domain: media_player
    sound_file:
      name: "Sound File"
      description: "The sound file to play (from media source)"
      selector:
        text:
    announce_volume:
      name: "Announce Volume Level"
      description: "The volume level to use for the announcement (0-1)"
      default: 0.5
      selector:
        number:
          min: 0
          max: 1
          step: 0.1
    volume_reduction:
      name: "Volume Reduction"
      description: "How much to reduce the volume for the announcement (0-1)"
      default: 0.2
      selector:
        number:
          min: 0
          max: 1
          step: 0.1
    wait_time:
      name: "Wait Time"
      description: "How long to wait after playing before restoring volume (seconds)"
      default: 20
      selector:
        number:
          min: 1
          max: 300
          step: 1
    custom_triggers:
      name: "Custom Triggers"
      description: "Additional triggers to play the sound"
      default: []
      selector:
        object:
          multiple: true
          options:
            platform:
              name: "Platform"
              description: "Trigger platform"
              selector:
                select:
                  options:
                    - time
                    - sun
                    - state
            at:
              name: "Time"
              description: "Time to trigger (for time platform)"
              selector:
                time:
            event:
              name: "Event"
              description: "Sun event (for sun platform)"
              selector:
                select:
                  options:
                    - sunrise
                    - sunset
            entity_id:
              name: "Entity"
              description: "Entity to monitor (for state platform)"
              selector:
                entity:
            from:
              name: "From State"
              description: "State to trigger from"
              selector:
                text:
            to:
              name: "To State"
              description: "State to trigger to"
              selector:
                text:

trigger:
  - platform: time
    at: !input at
  - platform: sun
    event: !input event
  - platform: state
    entity_id: !input entity_id
    from: !input from
    to: !input to
  - !input custom_triggers

action:
  - service: script.play_sound_with_volume_control
    data:
      media_player: !input media_player
      sound_file: !input sound_file
      announce_volume: !input announce_volume
      volume_reduction: !input volume_reduction
      wait_time: !input wait_time

mode: single 