blueprint:
  name: "[CDA] 🔔 Scheduled Bell Sound"
  description: "Play a sound at specific times with volume control"
  domain: automation
  input:
    media_player:
      name: "Media Player"
      description: "The media player to play the sound"
      selector:
        entity:
          domain: media_player
    sound_file:
      name: "Sound File"
      description: "The sound file to play (from media source)"
      selector:
        text:
    announce_volume:
      name: "Announce Volume Level"
      description: "The volume level to use for the announcement (0-1)"
      default: 0.5
      selector:
        number:
          min: 0
          max: 1
          step: 0.1
    volume_reduction:
      name: "Volume Reduction"
      description: "How much to reduce the volume for the announcement (0-1)"
      default: 0.2
      selector:
        number:
          min: 0
          max: 1
          step: 0.1
    wait_time:
      name: "Wait Time"
      description: "How long to wait after playing before restoring volume (seconds)"
      default: 20
      selector:
        number:
          min: 1
          max: 300
          step: 1
    time_triggers:
      name: "Time Triggers"
      description: "Times to trigger the sound"
      default: []
      selector:
        entity:
          multiple: true
          filter: 
            - domain: input_datetime
    sun_triggers:
      name: "Sun Triggers"
      description: "Sun events to trigger the sound"
      default: []
      selector:
        entity:
          multiple: true
          filter: 
            - domain: input_datetime
    state_triggers:
      name: "State Triggers"
      description: "State changes to trigger the sound"
      default: []
      selector:
        entity:
          multiple: true
          filter: 
            - domain: input_boolean
    event_triggers:
      name: "Event Triggers"
      description: "Events to trigger the sound"
      default: []
      selector:
        entity:
          multiple: true
          filter: 
            - domain: input_boolean
    mqtt_triggers:
      name: "MQTT Triggers"
      description: "MQTT topics to trigger the sound"
      default: []
      selector:
        entity:
          multiple: true
          filter: 
            - domain: input_text

trigger:
  # Time triggers
  - platform: time
    at: !input time_triggers[0]
  - platform: time
    at: !input time_triggers[1]
  - platform: time
    at: !input time_triggers[2]
  # Sun triggers
  - platform: sun
    event: !input sun_triggers[0]
  - platform: sun
    event: !input sun_triggers[1]
  # State triggers
  - platform: state
    entity_id: !input state_triggers[0]
  - platform: state
    entity_id: !input state_triggers[1]
  # Event triggers
  - platform: event
    event_type: !input event_triggers[0]
  - platform: event
    event_type: !input event_triggers[1]
  # MQTT triggers
  - platform: mqtt
    topic: !input mqtt_triggers[0]
  - platform: mqtt
    topic: !input mqtt_triggers[1]

action:
  - service: script.play_sound_with_volume_control
    data:
      media_player: !input media_player
      sound_file: !input sound_file
      announce_volume: !input announce_volume
      volume_reduction: !input volume_reduction
      wait_time: !input wait_time

mode: single 