# Variables
{% set cover_name = "Living Room Blind" %}
{% set switch_entity = "switch.living_room_blind" %}
{% set position_helper = "input_text.living_room_blind_position" %}
{% set direction_helper = "input_text.living_room_blind_direction" %}
{% set travel_time = 30 %}

# Example configuration.yaml entry
cover:
  - platform: template
    covers:
      {{ cover_name | lower | replace(' ', '_') }}:
        friendly_name: "{{ cover_name }}"
        unique_id: {{ cover_name | lower | replace(' ', '_') }}_template
        value_template: "{{ states(position_helper) | int }}"
        open_cover:
          service: script.set_blind_position
          data:
            blind_switch: {{ switch_entity }}
            last_state: {{ position_helper }}
            travel_time: {{ travel_time }}
            target_position: "100% (Open)"
        close_cover:
          service: script.set_blind_position
          data:
            blind_switch: {{ switch_entity }}
            last_state: {{ position_helper }}
            travel_time: {{ travel_time }}
            target_position: "0% (Closed)"
        stop_cover:
          service: switch.turn_off
          data:
            entity_id: {{ switch_entity }}
        set_cover_position:
          service: script.set_blind_position
          data:
            blind_switch: {{ switch_entity }}
            last_state: {{ position_helper }}
            travel_time: {{ travel_time }}
            target_position: >
              {% if position <= 25 %}
                "0% (Closed)"
              {% elif position <= 50 %}
                "25%"
              {% elif position <= 75 %}
                "50%"
              {% else %}
                "75%"
              {% endif %}
        icon_template: >
          {% if is_state(switch_entity, 'on') %}
            {% if states(direction_helper) == 'opening' %}
              mdi:arrow-up-bold
            {% else %}
              mdi:arrow-down-bold
            {% endif %}
          {% else %}
            {% if states(position_helper) | int == 0 %}
              mdi:window-closed
            {% elif states(position_helper) | int == 100 %}
              mdi:window-open
            {% else %}
              mdi:window-shutter
            {% endif %}
          {% endif %}

# Required input_text helpers
input_text:
  {{ position_helper.split('.')[1] }}:
    name: "{{ cover_name }} Position"
    initial: "0"
  {{ direction_helper.split('.')[1] }}:
    name: "{{ cover_name }} Direction"
    initial: "stopped"

# Automation to track blind state
automation:
  - alias: "Track {{ cover_name }} State"
    description: "Track the state of the {{ cover_name }}"
    trigger:
      - platform: state
        entity_id: {{ switch_entity }}
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: {{ switch_entity }}
                state: "on"
            sequence:
              - service: input_text.set_value
                data:
                  entity_id: {{ direction_helper }}
                  value: >
                    {% if states(position_helper) | int == 0 %}
                      opening
                    {% elif states(position_helper) | int == 100 %}
                      closing
                    {% else %}
                      {{ states(direction_helper) }}
                    {% endif %}
        default:
          - service: input_text.set_value
            data:
              entity_id: {{ direction_helper }}
              value: "stopped" 